export const GET_DATA = "GET_DATA";

export const SET_USERS = "ADD_USERS";
export const ADD_QUESTION_TO_USER = "ADD_QUESTION_TO_USER";

export const SET_QUESTIONS = "SET_QUESTIONS";

export const CREATE_QUESTION = "CREATE_QUESTION";

export const SET_QUESTION = "SET_QUESTION_IN_QUESTIONS";

export const ANSWER_QUESTION = "ANSWER_QUESTION";


export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";